export interface IActionType {
  [key: string]: string;
}

const actionTypes: IActionType = {
  GET_ALL_START: "GET_ALL_START",
  GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
  GET_ALL_ERROR: "GET_ALL_ERROR",
  GET_POST_COMMENTS_START: "GET_POST_COMMENTS_START",
  GET_POST_COMMENTS_SUCCESS: "GET_POST_COMMENTS_SUCCESS",
  GET_POST_COMMENTS_ERROR: "GET_POST_COMMENTS_ERROR",
};

export default actionTypes;
